APT::FTPArchive::Release {
  Origin "Atsign";
  Label "NoPorts Repository";
  Suite "stable";
  Codename "stable";
  Architectures "amd64 armhf arm64 riscv64 i386";
  Components "main";
  Description "NoPorts package repository";
};