name: Update APT Metadata
on:
  repository_dispatch:
    types: [new-release]

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  rebuild-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push metadata updates to this repo
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup GPG
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 -d > private.key
          gpg --import private.key
          rm private.key

      - name: Download Release Packages
        env:
          # Use the local, short-lived token instead of a PAT
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download --repo atsign-foundation/noports \
            --pattern "*.deb" --dir incoming/

      - name: Rebuild APT Structure
        working-directory: ./docs
        run: |
          # Define supported architectures
          # NB i386 is a 'shadow' arch with no actual packages.
          # Needed to avoid notifications from systems that
          # support i386 and amd64.
          ARCHS=("amd64" "armhf" "arm64" "riscv64" "i386")
          
          mkdir -p pool/main
          mv ../incoming/*.deb pool/main/ || true

          # Prune old packages: Keep only the 4 most recent releases
          echo "Pruning older releases..."
          VERSIONS=$(ls pool/main/noports_*.deb | xargs -n1 basename | cut -d'_' -f2 | sort -u -V)
          NUM_VERSIONS=$(echo "$VERSIONS" | wc -l)
          if [ "$NUM_VERSIONS" -gt 4 ]; then
            KEEP=4
            OLD_VERSIONS=$(echo "$VERSIONS" | head -n -$KEEP)
            for VER in $OLD_VERSIONS; do
              echo "Removing version $VER"
              rm pool/main/noports_${VER}_*.deb
            done
          fi

          for ARCH in "${ARCHS[@]}"; do
            mkdir -p dists/stable/main/binary-$ARCH
            # Scan only for the specific architecture
            apt-ftparchive --arch $ARCH packages pool/main > dists/stable/main/binary-$ARCH/Packages
            gzip -9fk dists/stable/main/binary-$ARCH/Packages
          done

          # Generate Release metadata
          apt-ftparchive -c ../apt-release.conf release dists/stable > dists/stable/Release
          
          # Sign the repo
          gpg --yes --clearsign -o dists/stable/InRelease dists/stable/Release
          gpg --yes -abs -o dists/stable/Release.gpg dists/stable/Release

      - name: Commit and Push
        run: |
          git config user.name "Atsign Robot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/.
          git commit -m "Update repository metadata - gha${{github.run_number}}"
          git push origin trunk
